# Generated by Django 4.1.4 on 2022-12-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quarterback_anticipation_quarterback_arm_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterback',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
