# Generated by Django 4.1.4 on 2022-12-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quarterback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterback',
            name='school',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
