# Generated by Django 4.1.4 on 2022-12-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quarterback_school_alter_quarterback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningback',
            name='school',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
