# Generated by Django 4.1.4 on 2022-12-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_runningback_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterback',
            name='intangebles',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
