# Generated by Django 4.1.4 on 2022-12-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_quarterback_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterback',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
