# Generated by Django 4.1.4 on 2022-12-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cornerback_ball_skills_cornerback_cod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idl',
            old_name='shed',
            new_name='rund',
        ),
    ]
