# Generated by Django 4.1.4 on 2022-12-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_idl_rund_edge_motor_idl_motor_idl_shed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='strength',
            new_name='speed_rush',
        ),
    ]
