# Generated by Django 4.1.4 on 2022-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_strength_edge_speed_rush'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='strength',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
