# Generated by Django 4.1.4 on 2022-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_edge_strength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cornerback',
            old_name='strength',
            new_name='transitions',
        ),
        migrations.AddField(
            model_name='linebacker',
            name='blitz',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
