# Generated by Django 4.1.4 on 2022-12-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_strength_cornerback_transitions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
