# Generated by Django 4.1.4 on 2022-12-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_prospect_quarterback_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerback',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='edge',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='idl',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='iol',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='linebacker',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='runningback',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='safety',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='tackle',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='tightend',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
        migrations.AddField(
            model_name='widereceiver',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
    ]
