# Generated by Django 4.1.4 on 2022-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_cornerback_prospect_edge_prospect_idl_prospect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='position',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
