# Generated by Django 4.1.4 on 2022-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_prospect_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='position',
            field=models.CharField(max_length=4),
        ),
    ]
