# Generated by Django 4.1.4 on 2022-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_prospect_name_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='school_link',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
