# Generated by Django 4.1.4 on 2022-12-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_prospect_school_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
